### ISSUE TITLE
Incorrect import in Docs, SDPMChunker reference

### ISSUE THREAD

**Issue by Om-Alve** [bhavnicksm/chonkie#16]
The import should be SDPMChunker in the code snippet here : https://github.com/bhavnicksm/chonkie/blob/main/DOCS.md#sdpmchunker

![image](https://github.com/user-attachments/assets/039d1f3f-22dd-49b0-9fd0-3c87fe1e2da6)

**Comment by bhavnicksm** [comment]
Yes! That's a typo that got missed...

Thanks for pointing it out 😄 will fix it
