### ISSUE TITLE
ImportError: cannot import name 'tokenizer' from 'tokenizers' (/usr/local/lib/python3.10/site-packages/tokenizers/__init__.py) 

### ISSUE THREAD

**Issue by abchbx** [bhavnicksm/chonkie#25]
怎么解决？

**Comment by bhavnicksm** [comment]
Hey @abchbx!

You might be making a minor spelling mistake here, could you try with `Tokenizer` (capital T) instead, like this:

```python
from tokenizers import Tokenizer

tokenizer = Tokenizer.from_pretrained("gpt2")
```

Hope this resolves the issue, closing the issue but you may re-open if you're still facing the same issue.
