### ISSUE TITLE
[BUG]AttributeError: 'SentenceTransformer' object has no attribute 'similarity'

### ISSUE THREAD

**Issue by heweapon** [bhavnicksm/chonkie#26]
**Describe the bug**
When I attempted to run Semantic Splitting, the following error occurred

**Code**
from chonkie.chunker.semantic import SemanticChunker

text = ""
chunker = SemanticChunker(
        embedding_model=r"D:\dl_code\rag_nel\data\model\all-MiniLM-L6-v2",
        max_chunk_size=512,
        similarity_threshold=0.5,
    )
chunks = chunker.chunk(text)
for chunk in chunks:
    print(f"chunk: {chunk}")

**Error**
Traceback (most recent call last):
  File "D:\dl_code\textsplit\chonkie_test.py", line 49, in <module>
    chunks = chunker.chunk(text)
  File "C:\Users\ustc\anaconda3\envs\torch222\lib\site-packages\chonkie\chunker\semantic.py", line 393, in chunk
    sentence_groups = self._group_sentences(sentences)
  File "C:\Users\ustc\anaconda3\envs\torch222\lib\site-packages\chonkie\chunker\semantic.py", line 286, in _group_sentences
    similarity = self._get_semantic_similarity(
  File "C:\Users\ustc\anaconda3\envs\torch222\lib\site-packages\chonkie\chunker\semantic.py", line 242, in _get_semantic_similarity
    similarity = self.embedding_model.similarity(embedding1, embedding2)
  File "C:\Users\ustc\anaconda3\envs\torch222\lib\site-packages\torch\nn\modules\module.py", line 1688, in __getattr__
    raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")
AttributeError: 'SentenceTransformer' object has no attribute 'similarity'

**Comment by bhavnicksm** [comment]
Hey @heweapon 

<img width="824" alt="image" src="https://github.com/user-attachments/assets/eb165f2b-35da-4ab8-9189-ec133c4f7c73">

It seems to work for me; could I ask for some more info? 

Could you try loading the model from the Hub directly instead of an offline model? If that doesn't work, could you tell me your package versions in your env?

**Comment by bhavnicksm** [comment]
This should show up in the chunker if your packages are up-to-date and well set-up. 

<img width="927" alt="image" src="https://github.com/user-attachments/assets/4ee86443-3a7f-4ddd-98c1-a3b5e4a754d5">

**Comment by heweapon** [comment]
> This should show up in the chunker if your packages are up-to-date and well set-up.
> 
> <img alt="image" width="927" src="https://private-user-images.githubusercontent.com/11348086/385677189-4ee86443-3a7f-4ddd-98c1-a3b5e4a754d5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE0ODg3MTQsIm5iZiI6MTczMTQ4ODQxNCwicGF0aCI6Ii8xMTM0ODA4Ni8zODU2NzcxODktNGVlODY0NDMtM2E3Zi00ZGRkLTk4YzEtYTNiNWU0YTc1NGQ1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTEzVDA5MDAxNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQyNjRkOTExMDRkZTJhZTg0MGU2NjYxNmJmZDNkMzkzNGY1NWEzYzhmN2IyODc2ZGIyMThmZTMyNTYyMDczMWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.IQ25lomkrJtwxq0VqGDN-cW4VT_FmkB_qE73_D9E4Tk">

Alright, thank you very much! I resolved the issue after updating the version of my sentence_transformers package.

**Comment by bhavnicksm** [comment]
Hey @heweapon, could you tell me which version you were running earlier?

**Comment by heweapon** [comment]
> Hey @heweapon, could you tell me which version you were running earlier? It would help me fix the dependencies so such issues don't happen in the future.

sentence-transformers-2.7.0

**Comment by bhavnicksm** [comment]
Thanks! Just checked that the dependencies do indeed work only beyond `sentence-transformers==2.3.0` but it might be that downloaded models don't come with `similarity`

Will test it out, for now closing this issue.
