### ISSUE TITLE
[BUG] Chunkers failing the test of recronstruction

### ISSUE THREAD

**Issue by mrmps** [bhavnicksm/chonkie#42]
**Describe the bug**
When chunking, observability is necessary. 

But how do you create observability?
Well, you look at the splits in the original text and you then look at the chunks.

What results is something like this:
<img width="1682" alt="image" src="https://github.com/user-attachments/assets/2dfef022-8b4c-4c47-9a0c-b762b565e493">

What important is that if we chunk text, and:
```
reconstructed_text = "".join(text[chunk.start_index:chunk.end_index] for chunk in chunks)
```
reconstructed text should be the same as the original text. Otherwise, observability is much harder to achieve.

Therefore, I propose this test:
```
# Function to test all chunking strategies
def test_all_chunkers(chunkers, text):
    for name, chunker in chunkers.items():
        print(f"Testing {name}...")
        chunks = chunker.chunk(text)

        # Test each chunk for index correctness
        for i, chunk in enumerate(chunks):
            assert text[chunk.start_index:chunk.end_index] == chunk.text, \
                f"Test failed for {name}, chunk {i}: Indices do not match text"

        # Test that all chunks together form the original text
        reconstructed_text = "".join(text[chunk.start_index:chunk.end_index] for chunk in chunks)
        assert reconstructed_text == text, \
            f"Test failed for {name}: Reconstructed text does not match original"

        print(f"{name} passed all tests!")

# Sample input text
texts = ["This is sentence " + str(n) + '.' for n in range(100)]
text = " ".join(texts)

# Initialize all chunkers
tokenizer = AutoTikTokenizer.from_pretrained("gpt2")

chunkers = {
    "SentenceChunker": SentenceChunker(
        tokenizer=tokenizer, chunk_size=50, chunk_overlap=10, min_sentences_per_chunk=1
    ),
    "TokenChunker": TokenChunker(
        tokenizer=tokenizer, chunk_size=50, chunk_overlap=10
    ),
    "WordChunker": WordChunker(
        tokenizer=tokenizer, chunk_size=50, chunk_overlap=10, mode="advanced"
    ),
    "SemanticChunker": SemanticChunker(
        embedding_model="all-minilm-l6-v2", max_chunk_size=50, similarity_threshold=0.7
    ),
    "SDPMChunker": SDPMChunker(
        embedding_model="all-minilm-l6-v2", max_chunk_size=50, similarity_threshold=0.7, skip_window=1
    ),
}

# Run the tests
test_all_chunkers(chunkers, text)
```

Text can be anything, but ideally it would be a complex document like:
https://r.jina.ai/https://docs.together.ai/docs/how-to-implement-contextual-rag-from-anthropic. This contains code snippets, markdown, and all kinds of things that make it good for tests.

**Comment by mrmps** [comment]
Right now this test fails, I believe for all Chonking strats.

**Comment by bhavnicksm** [comment]
Hey @mrmps!

Thanks for opening the issue 😄 

That's valid. Hold on, I'll just test it out and add this test to the tests as well~ 

Regarding coding, markdown, and JSON, I believe they are fundamentally challenging for chunkers to handle and more often you would see them being handled separately. I believe that may become an active area for development for Chonkie as well. And definitely a focus for the future. 

Thanks!

**Comment by mrmps** [comment]
Appreciate it! Yes, chunking code is challenging.

**Comment by mrmps** [comment]
@bhavnicksm I opened a new PR with the needed test, but most Chunkers seem to fail it.

The token chunker also seems to still return token indexes, not character indexes
<img width="1830" alt="image" src="https://github.com/user-attachments/assets/69e8ba76-98fa-4d38-9840-1167dba66846">

**Comment by bhavnicksm** [comment]
Hey @mrmps! 

Sorry, I couldn't check this till now. 
I'll look into this by EOD to understand where they are failing and put a patch in. 

Thanks!

**Comment by bhavnicksm** [comment]
@mrmps, 

Added #53 that adds the reconstruction tests and refactors the Chunkers to work on this test. Will look at more optimal implementations (currently the splitting mech. is quite slow, unfortunately).

Closing with this, please re-open if you're still facing the issue.

Thanks!

**Comment by armsp** [comment]
@mrmps quick question: What tool are you using for viewing the input text vs the chunks that are created?
