### ISSUE TITLE
[help] failed on SemanticChunker's example

### ISSUE THREAD

**Issue by mozz85** [bhavnicksm/chonkie#61]
**Describe the bug**
Failed to load Model2VecEmbeddings: 401 Client Error

**To Reproduce**
`from chonkie import SemanticChunker

chunker = SemanticChunker(
    embedding_model="all-minilm-l6-v2",
    chunk_size=512,
    similarity_threshold=0.7
)

chunks = chunker.chunk("Some text with semantic meaning to chunk appropriately.")
for chunk in chunks:
    print(f"Chunk: {chunk.text}")
    print(f"Number of semantic sentences: {len(chunk.sentences)}")`

**Expected behavior**
`
D:\developTools\anaconda3_531\envs\SentenceBD\lib\site-packages\chonkie\embeddings\auto.py:56: UserWarning: Failed to load Model2VecEmbeddings: 401 Client Error. (Request ID: Root=1-6743344c-380c8d8f2f3bcbb56a12f98d;80558796-934f-48cb-8f27-013b2d414fe0)

Repository Not Found for url: https://huggingface.co/all-minilm-l6-v2/resolve/main/model.safetensors.
Please make sure you specified the correct `repo_id` and `repo_type`.
If you are trying to access a private or gated repo, make sure you are authenticated.
Invalid username or password.
  warnings.warn(f"Failed to load {embeddings_cls.__name__}: {e}")
Traceback (most recent call last):
  File "e:\develop\python_projects\Subtitle_Adjustment_Tool\format_text.py", line 3, in <module>
    chunker = SemanticChunker(
  File "D:\developTools\anaconda3_531\envs\SentenceBD\lib\site-packages\chonkie\chunker\semantic.py", line 116, in __init__
    super().__init__(self.embedding_model.get_tokenizer_or_token_counter())
AttributeError: 'NoneType' object has no attribute 'get_tokenizer_or_token_counter'
`

**Screenshots**
![image](https://github.com/user-attachments/assets/35b50dd2-0416-4858-adfe-53337a8be88c)

**Comment by bhavnicksm** [comment]
Hey @mozz85, 

Could you try with the new patch release version `v0.2.1.post1` and let me know if you still face the issue? 

Thanks!

**Comment by mozz85** [comment]
sure. hold on a sec

**Comment by mozz85** [comment]
I need to do some google about how to import package from source. LOL
I'll let you know if it worked or not after that

**Comment by bhavnicksm** [comment]
Hey @mozz85, 

If you update the chonkie package to the latest version via the following command, 

```bash
pip install -U chonkie
```

and then run the code you were trying earlier, 

```
from chonkie import SemanticChunker

chunker = SemanticChunker(
     embedding_model="all-minilm-l6-v2",
     chunk_size=512,
     similarity_threshold=0.7
)

chunks = chunker.chunk("Some text with semantic meaning to chunk appropriately.")
for chunk in chunks:
    print(f"Chunk: {chunk.text}")
    print(f"Number of semantic sentences: {len(chunk.sentences)}")
```

it should work for you now!

Here's me trying it in a colab notebook, 

<img width="763" alt="Screenshot 2024-11-24 at 8 31 39 PM" src="https://github.com/user-attachments/assets/c96c6118-d4ae-4084-b359-20d4e05fadd2">

Thanks!

**Comment by mozz85** [comment]
Traceback (most recent call last):
  File "e:\develop\python_projects\Subtitle_Adjustment_Tool\format_text.py", line 3, in <module>
    chunker = SemanticChunker(
  File "D:\developTools\anaconda3_531\envs\SentenceBD\lib\site-packages\chonkie\chunker\semantic.py", line 120, in __init__
    super().__init__(self.embedding_model.get_tokenizer_or_token_counter())
AttributeError: 'NoneType' object has no attribute 'get_tokenizer_or_token_counter'

**Comment by bhavnicksm** [comment]
Hey @mozz85, 

Could you check if you have `sentence-transformers>=2.3.0` in your environment? 

Another potential thing to try out is running the following piece of code, 

```python
from chonkie import SentenceTransformerEmbeddings

emb = SentenceTransformerEmbeddings("all-minilm-l6-v2")
print(emb)
# output: SentenceTransformerEmbeddings(model=all-minilm-l6-v2)
```

**Comment by mozz85** [comment]
I don't have the sentence-transformers in my environment
```
(SentenceBD) E:\develop\python_projects\Subtitle_Adjustment_Tool\chonkie-0.2.1.post1>pip show sentence-transformers
WARNING: Package(s) not found: sentence-transformers
```

**Comment by bhavnicksm** [comment]
Hey @mozz85, 

Ah, that might be the issue, but it's surprising you got no error message from Chonkie (that might be a bug; I'll add more error messages)

Please try this:

```bash
pip install -U "chonkie[st]"
```

Thanks!

**Comment by bhavnicksm** [comment]
@mozz85, 

> I installed the chonkie by the command `pip install chonkie[semantic]`

So current `semantic` installs only the `Model2Vec` module, which is the lightest, fastest way to do it. But the `Model2Vec` doesn't load sentence-transformer models at the moment. 

You can try running the SemanticChunker directly, without passing a string model name, which would defualt to the `Model2Vec` model. Alternatively, you can install the `chonkie[st]` optional dependency installation and run sentence-transformer models with it!

The documentation might be a bit lacking; sorry if it wasn't clear in it!

Thanks!

**Comment by mozz85** [comment]
thanks for your clarification.

I tried both your method. they worked just fine.

The idea to make it the lightest and fastest is awesome.

**Comment by bhavnicksm** [comment]
Perfect! Glad to sort it out for you, @mozz85! 

Let me know if you have any further issues with Chonkie.

Thanks!
